[build]
command = "npm run build"
publish = ".output/public"
functions = ".output/server"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"