/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as WorkshopsIdRouteImport } from './routes/workshops.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardRegistrationsRouteImport } from './routes/_authenticated/dashboard.registrations'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard/admin.index'
import { Route as AuthenticatedDashboardAdminWorkshopsRouteImport } from './routes/_authenticated/dashboard/admin.workshops'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard/admin.users'
import { Route as AuthenticatedDashboardAdminSettingsRouteImport } from './routes/_authenticated/dashboard/admin.settings'
import { Route as AuthenticatedDashboardAdminRegistrationsRouteImport } from './routes/_authenticated/dashboard/admin.registrations'
import { Route as AuthenticatedDashboardAdminGalleryRouteImport } from './routes/_authenticated/dashboard/admin.gallery'
import { Route as AuthenticatedDashboardAdminBookingsRouteImport } from './routes/_authenticated/dashboard/admin.bookings'
import { Route as AuthenticatedDashboardAdminAvailabilityRouteImport } from './routes/_authenticated/dashboard/admin.availability'
import { Route as AuthenticatedDashboardAdminAnnouncementsRouteImport } from './routes/_authenticated/dashboard/admin.announcements'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIdRoute = WorkshopsIdRouteImport.update({
  id: '/workshops/$id',
  path: '/workshops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRegistrationsRoute =
  AuthenticatedDashboardRegistrationsRouteImport.update({
    id: '/dashboard/registrations',
    path: '/dashboard/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/dashboard/bookings',
    path: '/dashboard/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/dashboard/admin/',
    path: '/dashboard/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminWorkshopsRoute =
  AuthenticatedDashboardAdminWorkshopsRouteImport.update({
    id: '/dashboard/admin/workshops',
    path: '/dashboard/admin/workshops',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/dashboard/admin/users',
    path: '/dashboard/admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminSettingsRoute =
  AuthenticatedDashboardAdminSettingsRouteImport.update({
    id: '/dashboard/admin/settings',
    path: '/dashboard/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRegistrationsRoute =
  AuthenticatedDashboardAdminRegistrationsRouteImport.update({
    id: '/dashboard/admin/registrations',
    path: '/dashboard/admin/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminGalleryRoute =
  AuthenticatedDashboardAdminGalleryRouteImport.update({
    id: '/dashboard/admin/gallery',
    path: '/dashboard/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminBookingsRoute =
  AuthenticatedDashboardAdminBookingsRouteImport.update({
    id: '/dashboard/admin/bookings',
    path: '/dashboard/admin/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminAvailabilityRoute =
  AuthenticatedDashboardAdminAvailabilityRouteImport.update({
    id: '/dashboard/admin/availability',
    path: '/dashboard/admin/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminAnnouncementsRoute =
  AuthenticatedDashboardAdminAnnouncementsRouteImport.update({
    id: '/dashboard/admin/announcements',
    path: '/dashboard/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/workshops/$id': typeof WorkshopsIdRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/registrations': typeof AuthenticatedDashboardRegistrationsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/dashboard/admin/availability': typeof AuthenticatedDashboardAdminAvailabilityRoute
  '/dashboard/admin/bookings': typeof AuthenticatedDashboardAdminBookingsRoute
  '/dashboard/admin/gallery': typeof AuthenticatedDashboardAdminGalleryRoute
  '/dashboard/admin/registrations': typeof AuthenticatedDashboardAdminRegistrationsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin/workshops': typeof AuthenticatedDashboardAdminWorkshopsRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/workshops/$id': typeof WorkshopsIdRoute
  '/workshops': typeof WorkshopsIndexRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/registrations': typeof AuthenticatedDashboardRegistrationsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/dashboard/admin/availability': typeof AuthenticatedDashboardAdminAvailabilityRoute
  '/dashboard/admin/bookings': typeof AuthenticatedDashboardAdminBookingsRoute
  '/dashboard/admin/gallery': typeof AuthenticatedDashboardAdminGalleryRoute
  '/dashboard/admin/registrations': typeof AuthenticatedDashboardAdminRegistrationsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin/workshops': typeof AuthenticatedDashboardAdminWorkshopsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/workshops/$id': typeof WorkshopsIdRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/registrations': typeof AuthenticatedDashboardRegistrationsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/_authenticated/dashboard/admin/availability': typeof AuthenticatedDashboardAdminAvailabilityRoute
  '/_authenticated/dashboard/admin/bookings': typeof AuthenticatedDashboardAdminBookingsRoute
  '/_authenticated/dashboard/admin/gallery': typeof AuthenticatedDashboardAdminGalleryRoute
  '/_authenticated/dashboard/admin/registrations': typeof AuthenticatedDashboardAdminRegistrationsRoute
  '/_authenticated/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/admin/workshops': typeof AuthenticatedDashboardAdminWorkshopsRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/reset-password'
    | '/workshops/$id'
    | '/workshops/'
    | '/dashboard/bookings'
    | '/dashboard/registrations'
    | '/dashboard/'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/availability'
    | '/dashboard/admin/bookings'
    | '/dashboard/admin/gallery'
    | '/dashboard/admin/registrations'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/admin/workshops'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/reset-password'
    | '/workshops/$id'
    | '/workshops'
    | '/dashboard/bookings'
    | '/dashboard/registrations'
    | '/dashboard'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/availability'
    | '/dashboard/admin/bookings'
    | '/dashboard/admin/gallery'
    | '/dashboard/admin/registrations'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/admin/workshops'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/reset-password'
    | '/workshops/$id'
    | '/workshops/'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/registrations'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/announcements'
    | '/_authenticated/dashboard/admin/availability'
    | '/_authenticated/dashboard/admin/bookings'
    | '/_authenticated/dashboard/admin/gallery'
    | '/_authenticated/dashboard/admin/registrations'
    | '/_authenticated/dashboard/admin/settings'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/admin/workshops'
    | '/_authenticated/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WorkshopsIdRoute: typeof WorkshopsIdRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$id': {
      id: '/workshops/$id'
      path: '/workshops/$id'
      fullPath: '/workshops/$id'
      preLoaderRoute: typeof WorkshopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/registrations': {
      id: '/_authenticated/dashboard/registrations'
      path: '/dashboard/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof AuthenticatedDashboardRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/workshops': {
      id: '/_authenticated/dashboard/admin/workshops'
      path: '/dashboard/admin/workshops'
      fullPath: '/dashboard/admin/workshops'
      preLoaderRoute: typeof AuthenticatedDashboardAdminWorkshopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/dashboard/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/settings': {
      id: '/_authenticated/dashboard/admin/settings'
      path: '/dashboard/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/registrations': {
      id: '/_authenticated/dashboard/admin/registrations'
      path: '/dashboard/admin/registrations'
      fullPath: '/dashboard/admin/registrations'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/gallery': {
      id: '/_authenticated/dashboard/admin/gallery'
      path: '/dashboard/admin/gallery'
      fullPath: '/dashboard/admin/gallery'
      preLoaderRoute: typeof AuthenticatedDashboardAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/bookings': {
      id: '/_authenticated/dashboard/admin/bookings'
      path: '/dashboard/admin/bookings'
      fullPath: '/dashboard/admin/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/availability': {
      id: '/_authenticated/dashboard/admin/availability'
      path: '/dashboard/admin/availability'
      fullPath: '/dashboard/admin/availability'
      preLoaderRoute: typeof AuthenticatedDashboardAdminAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/announcements': {
      id: '/_authenticated/dashboard/admin/announcements'
      path: '/dashboard/admin/announcements'
      fullPath: '/dashboard/admin/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardRegistrationsRoute: typeof AuthenticatedDashboardRegistrationsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminAnnouncementsRoute: typeof AuthenticatedDashboardAdminAnnouncementsRoute
  AuthenticatedDashboardAdminAvailabilityRoute: typeof AuthenticatedDashboardAdminAvailabilityRoute
  AuthenticatedDashboardAdminBookingsRoute: typeof AuthenticatedDashboardAdminBookingsRoute
  AuthenticatedDashboardAdminGalleryRoute: typeof AuthenticatedDashboardAdminGalleryRoute
  AuthenticatedDashboardAdminRegistrationsRoute: typeof AuthenticatedDashboardAdminRegistrationsRoute
  AuthenticatedDashboardAdminSettingsRoute: typeof AuthenticatedDashboardAdminSettingsRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminWorkshopsRoute: typeof AuthenticatedDashboardAdminWorkshopsRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
  AuthenticatedDashboardRegistrationsRoute:
    AuthenticatedDashboardRegistrationsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAdminAnnouncementsRoute:
    AuthenticatedDashboardAdminAnnouncementsRoute,
  AuthenticatedDashboardAdminAvailabilityRoute:
    AuthenticatedDashboardAdminAvailabilityRoute,
  AuthenticatedDashboardAdminBookingsRoute:
    AuthenticatedDashboardAdminBookingsRoute,
  AuthenticatedDashboardAdminGalleryRoute:
    AuthenticatedDashboardAdminGalleryRoute,
  AuthenticatedDashboardAdminRegistrationsRoute:
    AuthenticatedDashboardAdminRegistrationsRoute,
  AuthenticatedDashboardAdminSettingsRoute:
    AuthenticatedDashboardAdminSettingsRoute,
  AuthenticatedDashboardAdminUsersRoute: AuthenticatedDashboardAdminUsersRoute,
  AuthenticatedDashboardAdminWorkshopsRoute:
    AuthenticatedDashboardAdminWorkshopsRoute,
  AuthenticatedDashboardAdminIndexRoute: AuthenticatedDashboardAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WorkshopsIdRoute: WorkshopsIdRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
